# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_data', models.CharField(max_length=100)),
                ('usergroup', models.CharField(choices=[('citizen', 'Citizen'), ('student', 'Student'), ('social worker', 'Social Worker'), ('public health', 'Public Health Professional'), ('researcher', 'Researcher')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('q1', models.CharField(max_length=1000)),
                ('c1', models.CharField(max_length=100)),
                ('submit_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question'),
        ),
    ]
