# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='c2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='c3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='c4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='c5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='q2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='q3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='q4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='q5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='c1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='q1',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
