# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20161229_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='c5',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
